---
- hosts: all
  become: true
  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: tag the docker image you just created
    command: docker tag simple-devops-image olajide85/simple-devops-image

  - name: push image to dockerhub
    command: docker push olajide85/simple-devops-image

  - name: remove local docker image from ansible server
    command: docker rmi simple-devops-image olajide85/simple-devops-image
    ignore_errors: yes
